# Generated by Django 5.0.1 on 2025-09-10 01:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Avaliação',
                'verbose_name_plural': 'Templates de Avaliação',
                'db_table': 'evaluations_evaluation_template',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('auto_avaliacao', 'Auto-avaliação'), ('avaliacao_superior', 'Avaliação do Superior'), ('avaliacao_360', 'Avaliação 360°'), ('avaliacao_pares', 'Avaliação de Pares')], default='avaliacao_superior', max_length=20, verbose_name='Tipo de Avaliação')),
                ('periodo_inicio', models.DateField(verbose_name='Início do Período')),
                ('periodo_fim', models.DateField(verbose_name='Fim do Período')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='rascunho', max_length=15, verbose_name='Status')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Nota Final')),
                ('comentario_geral', models.TextField(blank=True, verbose_name='Comentário Geral')),
                ('pontos_fortes', models.TextField(blank=True, verbose_name='Pontos Fortes')),
                ('pontos_melhoria', models.TextField(blank=True, verbose_name='Pontos de Melhoria')),
                ('metas_objetivos', models.TextField(blank=True, verbose_name='Metas e Objetivos')),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'evaluations_evaluation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Ciclo de Avaliação',
                'verbose_name_plural': 'Ciclos de Avaliação',
                'db_table': 'evaluations_evaluation_cycle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCycleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluating_in_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='evaluations.evaluationcycle', verbose_name='Ciclo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_in_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Participante do Ciclo',
                'verbose_name_plural': 'Participantes do Ciclo',
                'db_table': 'evaluations_cycle_participant',
                'ordering': ['funcionario__first_name', 'funcionario__last_name'],
                'unique_together': {('cycle', 'funcionario')},
            },
        ),
        migrations.AddField(
            model_name='evaluationcycle',
            name='funcionarios',
            field=models.ManyToManyField(through='evaluations.EvaluationCycleParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Funcionários'),
        ),
        migrations.AddField(
            model_name='evaluationcycle',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationtemplate', verbose_name='Template Padrão'),
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Peso do critério na avaliação final (1.00 = 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Peso')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem de exibição do critério', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='evaluations.evaluationtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
                'db_table': 'evaluations_evaluation_criteria',
                'ordering': ['template', 'ordem'],
                'unique_together': {('template', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluation', verbose_name='Avaliação')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcriteria', verbose_name='Critério')),
            ],
            options={
                'verbose_name': 'Pontuação da Avaliação',
                'verbose_name_plural': 'Pontuações das Avaliações',
                'db_table': 'evaluations_evaluation_score',
                'ordering': ['criterio__ordem'],
                'unique_together': {('avaliacao', 'criterio')},
            },
        ),
    ]
