site_name: PortalRH Documentation
site_description: Human Resources Management System documentation
site_author: GabrielDLobo
use_directory_urls: false

docs_dir: docs

theme:
  name: material
  palette:
    primary: navy blue
  font:
    text: Roboto

nav:
  - Home: index.md
  - Overview: overview.md
  - Prerequisites: prerequisites.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Guidelines and Standards: guidelines.md
  - Project Structure: project-structure.md
  - API Endpoints: api-endpoints.md
  - System Modeling: system-modeling.md
  - Authentication and Security: authentication-security.md
  - Development: development.md
  - Testing: testing.md
  - Deploy: deploy.md
  - Contribution: contributing.md
  - Image Projects: gallery.md
  - Release Notes: release-notes.md
  - Update Log: UPDATE_LOG.md

plugins:
  - search

markdown_extensions:
  - fenced_code
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
