# Generated by Django 5.0.1 on 2025-09-10 15:11

import django.core.validators
import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato XXX.XXX.XXX-XX')], verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('marital_status', models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)'), ('stable_union', 'União Estável')], max_length=20, verbose_name='Estado Civil')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$', 'Telefone deve estar no formato (XX) XXXXX-XXXX')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('street_address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=10, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP deve estar no formato XXXXX-XXX')], verbose_name='CEP')),
                ('pis_pasep', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{5}\\.\\d{2}-\\d{1}$', 'PIS/PASEP deve estar no formato XXX.XXXXX.XX-X')], verbose_name='PIS/PASEP')),
                ('work_card_number', models.CharField(blank=True, max_length=20, verbose_name='Número da CTPS')),
                ('work_card_series', models.CharField(blank=True, max_length=10, verbose_name='Série da CTPS')),
                ('education_level', models.CharField(choices=[('elementary', 'Ensino Fundamental'), ('high_school', 'Ensino Médio'), ('technical', 'Técnico'), ('undergraduate', 'Superior'), ('postgraduate', 'Pós-graduação'), ('masters', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20, verbose_name='Escolaridade')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('bank_code', models.CharField(max_length=3, verbose_name='Código do Banco')),
                ('agency_number', models.CharField(max_length=10, verbose_name='Agência')),
                ('account_number', models.CharField(max_length=20, verbose_name='Conta')),
                ('account_type', models.CharField(choices=[('checking', 'Corrente'), ('savings', 'Poupança')], default='checking', max_length=20, verbose_name='Tipo de Conta')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('status', models.CharField(choices=[('pending', 'Documentação Pendente'), ('under_review', 'Em Análise'), ('approved', 'Aprovado'), ('active', 'Ativo'), ('inactive', 'Inativo')], default='pending', max_length=20, verbose_name='Status')),
                ('admission_completed', models.BooleanField(default=False, verbose_name='Documentação Completa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Iniciado'), ('documents_uploaded', 'Documentos Enviados'), ('under_review', 'Em Análise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('completed', 'Processo Concluído')], default='started', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('personal_info_completed', models.BooleanField(default=False, verbose_name='Informações Pessoais Preenchidas')),
                ('documents_uploaded', models.BooleanField(default=False, verbose_name='Documentos Enviados')),
                ('hr_review_completed', models.BooleanField(default=False, verbose_name='Revisão RH Completa')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_process', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Processo de Admissão',
                'verbose_name_plural': 'Processos de Admissão',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('birth_certificate', 'Certidão de Nascimento'), ('marriage_certificate', 'Certidão de Casamento'), ('education_certificate', 'Comprovante de Escolaridade'), ('work_card', 'Carteira de Trabalho'), ('medical_exam', 'Exame Admissional'), ('bank_document', 'Comprovante Bancário'), ('address_proof', 'Comprovante de Endereço'), ('other', 'Outros')], max_length=30, verbose_name='Tipo de Documento')),
                ('document_name', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('file', models.FileField(upload_to=employees.models.employee_documents_upload_path, verbose_name='Arquivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('is_required', models.BooleanField(default=True, verbose_name='Documento Obrigatório')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Documento Verificado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Documento do Funcionário',
                'verbose_name_plural': 'Documentos dos Funcionários',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
