# Generated by Django 5.0.1 on 2025-09-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='requires_password_change',
            field=models.BooleanField(default=False, verbose_name='Requer Troca de Senha'),
        ),
        migrations.CreateModel(
            name='PreAdmissionRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Pessoal do Colaborador')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('job_description', models.TextField(verbose_name='Descrição das Atividades')),
                ('work_schedule', models.CharField(max_length=100, verbose_name='Horário de Trabalho')),
                ('weekly_workload', models.CharField(choices=[('20h', '20 horas semanais'), ('30h', '30 horas semanais'), ('40h', '40 horas semanais'), ('44h', '44 horas semanais')], max_length=10, verbose_name='Jornada Semanal')),
                ('contract_type', models.CharField(choices=[('clt', 'CLT'), ('temporary', 'Temporário'), ('internship', 'Estágio'), ('freelancer', 'Freelancer'), ('pj', 'Pessoa Jurídica')], max_length=20, verbose_name='Tipo de Contrato')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('benefits', models.TextField(blank=True, verbose_name='Benefícios (vale-transporte, refeição, plano de saúde, etc.)')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('vacation_policy', models.TextField(blank=True, verbose_name='Política de Férias e Banco de Horas')),
                ('direct_manager', models.CharField(max_length=255, verbose_name='Nome do Gestor Direto')),
                ('employee_user_created', models.BooleanField(default=False, verbose_name='Usuário do funcionário criado')),
                ('temporary_password', models.CharField(blank=True, max_length=50, verbose_name='Senha temporária')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-mail enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pre_admissions', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_admission_rh', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Pré-admissão RH',
                'verbose_name_plural': 'Pré-admissões RH',
                'ordering': ['-created_at'],
            },
        ),
    ]
