# Generated by Django 5.0.1 on 2025-09-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_requires_password_change_preadmissionrh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='agency_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código do Banco'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Banco'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, choices=[('elementary', 'Ensino Fundamental'), ('high_school', 'Ensino Médio'), ('technical', 'Técnico'), ('undergraduate', 'Superior'), ('postgraduate', 'Pós-graduação'), ('masters', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)'), ('stable_union', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pis_pasep',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='PIS/PASEP'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da CTPS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_card_series',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série da CTPS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
