# Generated by Django 5.0.1 on 2025-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='preadmissionrh',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('rg', 'RG'), ('birth_certificate', 'Certidão de Nascimento'), ('marriage_certificate', 'Certidão de Casamento'), ('education_certificate', 'Comprovante de Escolaridade'), ('work_card', 'Carteira de Trabalho'), ('medical_exam', 'Exame Admissional'), ('bank_document', 'Comprovante Bancário'), ('address_proof', 'Comprovante de Endereço'), ('other', 'Outros')], max_length=30, verbose_name='Tipo de Documento'),
        ),
    ]
