# Generated by Django 5.2.6 on 2026-08-19 19:58

import django.core.validators
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeedocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=employees.models.employee_documents_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo'),
        ),
    ]
