# Generated by Django 5.0.1 on 2025-09-10 01:50

import django.core.validators
import django.db.models.deletion
import staff.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'staff_department',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salário')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'Férias'), ('afastado', 'Afastado')], default='ativo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'staff_employee',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato de Trabalho'), ('rg', 'RG'), ('cpf', 'CPF'), ('titulo_eleitor', 'Título de Eleitor'), ('carteira_trabalho', 'Carteira de Trabalho'), ('comprovante_residencia', 'Comprovante de Residência'), ('diploma', 'Diploma'), ('certificado', 'Certificado'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo do Documento')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(upload_to=staff.models.employee_document_upload_path, verbose_name='Arquivo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.employee', verbose_name='Funcionário')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento do Funcionário',
                'verbose_name_plural': 'Documentos dos Funcionários',
                'db_table': 'staff_employee_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
