# Generated by Django 5.0.1 on 2025-09-10 01:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('max_dias_ano', models.PositiveIntegerField(help_text='Máximo de dias por ano', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de dias por ano')),
                ('requer_aprovacao', models.BooleanField(default=True, verbose_name='Requer aprovação')),
                ('antecedencia_minima', models.PositiveIntegerField(default=1, help_text='Antecedência mínima em dias', verbose_name='Antecedência mínima (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitação',
                'verbose_name_plural': 'Tipos de Solicitações',
                'db_table': 'leave_requests_leave_type',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('comentario_aprovacao', models.TextField(blank=True, verbose_name='Comentário da Aprovação')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='leave_requests/attachments/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_requests.leavetype', verbose_name='Tipo de Solicitação')),
            ],
            options={
                'verbose_name': 'Solicitação de Afastamento',
                'verbose_name_plural': 'Solicitações de Afastamento',
                'db_table': 'leave_requests_leave_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('dias_disponiveis', models.PositiveIntegerField(default=0, verbose_name='Dias Disponíveis')),
                ('dias_utilizados', models.PositiveIntegerField(default=0, verbose_name='Dias Utilizados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_requests.leavetype', verbose_name='Tipo de Solicitação')),
            ],
            options={
                'verbose_name': 'Saldo de Afastamentos',
                'verbose_name_plural': 'Saldos de Afastamentos',
                'db_table': 'leave_requests_leave_balance',
                'ordering': ['-ano', 'tipo__nome'],
                'unique_together': {('funcionario', 'tipo', 'ano')},
            },
        ),
    ]
