# Generated by Django 5.0.1 on 2025-09-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='dias_abono_pecuniario',
            field=models.PositiveIntegerField(blank=True, help_text='Número de dias vendidos como abono pecuniário (máximo 10 dias)', null=True, verbose_name='Dias de Abono Pecuniário'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='dias_gozo',
            field=models.PositiveIntegerField(blank=True, help_text='Número de dias que serão efetivamente gozados (apenas para férias)', null=True, verbose_name='Quantidade de Dias em Gozo'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tem_abono_pecuniario',
            field=models.BooleanField(default=False, verbose_name='Há Venda do Abono Pecuniário?'),
        ),
    ]
