# Generated by Django 5.0.1 on 2025-09-17 05:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('requer_aviso_previo', models.BooleanField(default=True, verbose_name='Requer Aviso Prévio')),
                ('permite_saque_fgts', models.BooleanField(default=False, verbose_name='Permite Saque FGTS')),
                ('gera_multa_fgts', models.BooleanField(default=False, verbose_name='Gera Multa 40% FGTS')),
                ('direito_seguro_desemprego', models.BooleanField(default=False, verbose_name='Direito ao Seguro Desemprego')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Motivo de Desligamento',
                'verbose_name_plural': 'Motivos de Desligamento',
                'db_table': 'termination_termination_reason',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TerminationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ultimo_dia', models.DateField(verbose_name='Último Dia de Trabalho')),
                ('data_desligamento', models.DateField(help_text='Data oficial do desligamento', verbose_name='Data de Desligamento')),
                ('justificativa', models.TextField(help_text='Descreva detalhadamente os motivos que levaram ao desligamento', max_length=2000, verbose_name='Justificativa Detalhada')),
                ('observacoes_rh', models.TextField(blank=True, max_length=1000, verbose_name='Observações do RH')),
                ('tem_aviso_previo', models.BooleanField(default=True, verbose_name='Há Aviso Prévio?')),
                ('dias_aviso_previo', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Dias de Aviso Prévio')),
                ('aviso_previo_indenizado', models.BooleanField(default=False, verbose_name='Aviso Prévio Indenizado?')),
                ('tem_ferias_vencidas', models.BooleanField(default=False, verbose_name='Possui Férias Vencidas?')),
                ('dias_ferias_vencidas', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Dias de Férias Vencidas')),
                ('tem_ferias_proporcionais', models.BooleanField(default=True, verbose_name='Possui Férias Proporcionais?')),
                ('dias_ferias_proporcionais', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Dias de Férias Proporcionais')),
                ('tem_decimo_proporcional', models.BooleanField(default=True, verbose_name='Possui 13º Proporcional?')),
                ('possui_equipamentos', models.BooleanField(default=False, verbose_name='Possui Equipamentos da Empresa?')),
                ('lista_equipamentos', models.TextField(blank=True, help_text='Liste todos os equipamentos, materiais e documentos que devem ser devolvidos', verbose_name='Lista de Equipamentos')),
                ('possui_acessos_sistemas', models.BooleanField(default=True, verbose_name='Possui Acessos a Sistemas?')),
                ('lista_acessos', models.TextField(blank=True, help_text='Liste todos os sistemas, aplicações e acessos que devem ser revogados', verbose_name='Lista de Acessos')),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('critica', 'Crítica')], default='normal', max_length=10, verbose_name='Urgência')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente_rh', 'Pendente Análise RH'), ('aprovada_rh', 'Aprovada pelo RH'), ('rejeitada_rh', 'Rejeitada pelo RH'), ('processando', 'Processando Rescisão'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=15, verbose_name='Status')),
                ('data_aprovacao_rh', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação RH')),
                ('comentario_aprovacao_rh', models.TextField(blank=True, verbose_name='Comentário da Aprovação RH')),
                ('valor_rescisao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total da Rescisão')),
                ('anexo_documentos', models.FileField(blank=True, help_text='Anexe documentos comprobatórios (advertências, cartas, etc.)', null=True, upload_to='termination/documents/', verbose_name='Documentos Anexos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovador_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_terminations', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador RH')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_requests', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termination.terminationreason', verbose_name='Motivo do Desligamento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_terminations', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante (Gestor)')),
            ],
            options={
                'verbose_name': 'Solicitação de Desligamento',
                'verbose_name_plural': 'Solicitações de Desligamento',
                'db_table': 'termination_termination_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('trct', 'TRCT - Termo de Rescisão'), ('aviso_previo', 'Aviso Prévio'), ('carta_desligamento', 'Carta de Desligamento'), ('termo_devolucao', 'Termo de Devolução de Equipamentos'), ('quitacao', 'Termo de Quitação'), ('outros', 'Outros Documentos')], max_length=20, verbose_name='Tipo de Documento')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('arquivo', models.FileField(upload_to='termination/generated_documents/', verbose_name='Arquivo')),
                ('gerado_automaticamente', models.BooleanField(default=False, verbose_name='Gerado Automaticamente')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('termination_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='termination.terminationrequest', verbose_name='Solicitação de Desligamento')),
            ],
            options={
                'verbose_name': 'Documento de Desligamento',
                'verbose_name_plural': 'Documentos de Desligamento',
                'db_table': 'termination_termination_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('documentacao', 'Documentação'), ('equipamentos', 'Equipamentos'), ('acessos', 'Acessos e Sistemas'), ('financeiro', 'Financeiro'), ('legal', 'Legal/Compliance'), ('outros', 'Outros')], max_length=15, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Item')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('termination_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='termination.terminationrequest', verbose_name='Solicitação de Desligamento')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Itens de Checklist',
                'db_table': 'termination_termination_checklist',
                'ordering': ['categoria', 'obrigatorio', 'descricao'],
            },
        ),
    ]
