# Generated by Django 5.0.1 on 2025-09-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminationreason',
            name='direito_seguro_desemprego',
        ),
        migrations.RemoveField(
            model_name='terminationreason',
            name='gera_multa_fgts',
        ),
        migrations.RemoveField(
            model_name='terminationreason',
            name='permite_saque_fgts',
        ),
        migrations.RemoveField(
            model_name='terminationreason',
            name='requer_aviso_previo',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='aviso_previo_indenizado',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='dias_aviso_previo',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='dias_ferias_proporcionais',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='dias_ferias_vencidas',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='lista_acessos',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='lista_equipamentos',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='possui_acessos_sistemas',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='possui_equipamentos',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='tem_aviso_previo',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='tem_decimo_proporcional',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='tem_ferias_proporcionais',
        ),
        migrations.RemoveField(
            model_name='terminationrequest',
            name='tem_ferias_vencidas',
        ),
        migrations.DeleteModel(
            name='TerminationChecklist',
        ),
    ]
