# Generated by Django 5.0.1 on 2025-09-30 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Relatório',
                'verbose_name_plural': 'Categorias de Relatórios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Relatório')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('report_type', models.CharField(choices=[('employees', 'Relatório de Funcionários'), ('terminations', 'Relatório de Desligamentos'), ('evaluations', 'Relatório de Avaliações'), ('leave_requests', 'Relatório de Solicitações de Férias'), ('admissions', 'Relatório de Admissões'), ('dashboard', 'Dashboard Resumo'), ('custom', 'Relatório Personalizado')], max_length=20, verbose_name='Tipo de Relatório')),
                ('query_config', models.JSONField(default=dict, help_text='Configurações para filtros, ordenação e campos', verbose_name='Configuração da Query')),
                ('output_formats', models.JSONField(default=list, help_text="Lista de formatos suportados: ['json', 'pdf', 'excel', 'csv']", verbose_name='Formatos de Saída')),
                ('default_format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='json', max_length=10, verbose_name='Formato Padrão')),
                ('columns_config', models.JSONField(default=dict, help_text='Configuração de quais colunas exibir e como formatá-las', verbose_name='Configuração de Colunas')),
                ('chart_config', models.JSONField(default=dict, help_text='Configurações para gráficos e visualizações', verbose_name='Configuração de Gráficos')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('allowed_roles', models.JSONField(default=list, help_text='Lista de perfis que podem acessar este relatório', verbose_name='Perfis Permitidos')),
                ('cache_duration', models.IntegerField(default=300, verbose_name='Duração do Cache (segundos)')),
                ('enable_cache', models.BooleanField(default=True, verbose_name='Habilitar Cache')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('version', models.IntegerField(default=1, verbose_name='Versão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Permitidos')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportcategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Agendamento')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('custom', 'Personalizado')], max_length=15, verbose_name='Frequência')),
                ('cron_expression', models.CharField(blank=True, help_text='Para frequência personalizada (formato: min hour day month weekday)', max_length=100, verbose_name='Expressão Cron')),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Formato de Saída')),
                ('parameters', models.JSONField(default=dict, help_text='Parâmetros fixos para execução automática', verbose_name='Parâmetros')),
                ('email_recipients', models.JSONField(default=list, help_text='Lista de emails para envio do relatório', verbose_name='Destinatários de Email')),
                ('send_email_on_success', models.BooleanField(default=True, verbose_name='Enviar Email em Sucesso')),
                ('send_email_on_failure', models.BooleanField(default=True, verbose_name='Enviar Email em Falha')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('disabled', 'Desabilitado')], default='active', max_length=15, verbose_name='Status')),
                ('last_execution', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('next_execution', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Execução')),
                ('execution_count', models.IntegerField(default=0, verbose_name='Contagem de Execuções')),
                ('success_count', models.IntegerField(default=0, verbose_name='Sucessos')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Falhas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Agendamento de Relatório',
                'verbose_name_plural': 'Agendamentos de Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameters', models.JSONField(default=dict, help_text='Parâmetros específicos desta execução', verbose_name='Parâmetros')),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Formato de Saída')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Status')),
                ('result_data', models.JSONField(default=dict, help_text='Resultado da execução em formato JSON', verbose_name='Dados do Resultado')),
                ('file_path', models.CharField(blank=True, help_text='Caminho para arquivo gerado (PDF, Excel, etc.)', max_length=500, verbose_name='Caminho do Arquivo')),
                ('execution_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Tempo de Execução (segundos)')),
                ('rows_processed', models.IntegerField(blank=True, null=True, verbose_name='Linhas Processadas')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data de expiração do arquivo gerado', null=True, verbose_name='Expira em')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Execução de Relatório',
                'verbose_name_plural': 'Execuções de Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome Personalizado')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parâmetros Salvos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Favorito de Relatório',
                'verbose_name_plural': 'Favoritos de Relatórios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['report_type', 'is_active'], name='reports_rep_report__11a031_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['created_by', 'is_active'], name='reports_rep_created_2b4a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['status', 'next_execution'], name='reports_rep_status_092276_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['template', 'status'], name='reports_rep_templat_a9968b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['template', 'status'], name='reports_rep_templat_36d6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['executed_by', 'created_at'], name='reports_rep_execute_07b8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status', 'created_at'], name='reports_rep_status_8339bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportbookmark',
            unique_together={('user', 'template')},
        ),
    ]
